spring:
  application:
    name: "crypto-recommendation-service"
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/piktiv-crypto-service
    username: postgres
    password:
    hikari:
      auto-commit: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog-master.xml

server:
  port: 8080

management:
  server:
    port: 9101
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure.include: "prometheus, health"
      base-path: "/"
      path-mapping:
        prometheus: "metrics"
  tracing:
    enabled: true
    propagation:
      consume: [ w3c, b3-multi, b3 ]
      produce: [ w3c, b3 ]

springdoc:
  api-docs:
    path: /api-docs

se.ai.crypto:
    supportedCryptos:
      - BTC
      - DOGE
      - ETH
      - LTC
      - XRP
    blockedIps:
      - 192.168.0.200
      - 192.168.0.201
      #- 0:0:0:0:0:0:0:1 ## Will block localhost
      #- 127.0.0.1 ## Will block localhost