version: '3'

services:
  ## Database service
  postgres:
    container_name: postgres
    image: postgres:17.6
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /data/postgres
    volumes:
      - ./postgres/data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
